"""Rendering: one JSON envelope, and tables for people. No business logic.

Two things this module exists to guarantee.

**One envelope shape, every command.** `results` is always a top-level array of
objects — including for `check`, which returns a single-element array rather
than the bare object it obviously "wants" to be. This repo has already been
bitten once by a command whose `--json` returned an object where its siblings
returned arrays (see CLAUDE.md on `seats --json`); a consumer that has to
branch on the command name is a consumer that will get it wrong.

**Sandbox numbers can never pass for real ones.** Against the sandbox host the
prices are mock data generated for development. Every row carries
`priceIsReal: false`, every printed line is prefixed, and `cars`/`sweep` refuse
to rank on price at all without `--sandbox-ok`. This is deliberately structural
rather than a warning in prose: prose competes with a user asking a direct
question in the moment, and loses. The failure it prevents — a confident,
specific, actionable dollar figure that is fiction — is worse than any of the
"nothing found" cases, because every one of those degrades legibly and this one
does not.
"""

from __future__ import annotations

import json
import sys
from typing import Iterable, Sequence

SCHEMA_VERSION = 1

#: Prefixed to every printed row when the numbers are mock data. Short enough
#: to survive a narrow terminal, explicit enough to survive being quoted alone.
SANDBOX_ROW_PREFIX = "SANDBOX — SAMPLE DATA, NOT A REAL PRICE"

SANDBOX_BANNER = (
    "SANDBOX: these prices are mock data generated by KAYAK for development. "
    "They are not quotes and bear no relation to real rates. Do not report "
    "them as prices."
)


def envelope(
    command: str,
    results: Sequence[dict],
    *,
    ok: bool = True,
    exit_code: int = 0,
    error: str | None = None,
    query: dict | None = None,
    meta: dict | None = None,
) -> dict:
    """The single response shape, for success and failure alike.

    `results` is present and a list even on the failure path, so a consumer can
    read `data["results"]` unconditionally.
    """
    return {
        "schema_version": SCHEMA_VERSION,
        "ok": ok,
        "command": command,
        "exit_code": exit_code,
        "error": error,
        "query": query or {},
        "count": len(results),
        "results": list(results),
        "meta": meta or {},
    }


def search_meta(
    search,
    *,
    sandbox: bool,
    requests_made: int,
    kept: int | None = None,
    parsed: int | None = None,
    rejected: dict[str, int] | None = None,
) -> dict:
    """Meta for a car search: what phase it reached, and what it cost.

    `partial` is the field an agent should branch on. `complete` says the
    search finished; anything else means the cheapest row is merely the
    cheapest *so far*.
    """
    status = getattr(search, "status", "") if search else ""
    return {
        "status": status,
        "complete": status == "complete",
        "partial": bool(status) and status != "complete",
        "requests": requests_made,
        "price_mode": getattr(search, "price_mode", "") if search else "",
        "currency": getattr(search, "currency", "") if search else "",
        "total_count": getattr(search, "total_count", None) if search else None,
        "parsed": parsed,
        "kept": kept,
        "sandbox": sandbox,
        "prices_are_mocked": sandbox,
        "filtered_out": dict(rejected or {}),
    }


def offer_row(offer, sandbox: bool) -> dict:
    """One offer as JSON: the trimmed projection, plus the honesty flag.

    Never the raw booking option — a 500-row response is megabytes of logo URLs
    and tracking tokens, all of which would land in an agent's context window.
    `--full` opts into the raw response for the rare case that needs it.
    """
    row = offer.summary()
    row["priceIsReal"] = not sandbox
    return row


def full_row(row: dict, sandbox: bool) -> dict:
    """One raw `results[]` row for `--full`, plus the honesty flag.

    The row is otherwise untouched — the reason to reach for `--full` is that
    the projection dropped a field, so re-shaping here would defeat it. The one
    key added is `priceIsReal`, because the guard has to survive someone
    reading a single row on its own: a raw row carries a real-looking
    `bookingOptions[].price.price` and nothing else on it says the number is
    mock data. A copy is returned so the search's own `raw` stays untouched.
    """
    return {**row, "priceIsReal": not sandbox}


def ranking_footer(ranked_by: str, fix: str = "") -> str:
    """The line printed under a table that is *not* ranked on price, or "".

    Shared by cars and hotels so the warning is worded once. A table whose top
    row is the nearest, or the most popular, reads exactly like a table whose
    top row is the cheapest — nothing in the columns distinguishes them — so
    the ranking has to be stated rather than inferred.
    """
    if ranked_by == "price":
        return ""
    note = (f"ordered by {ranked_by}, as the API returned them — "
            f"the first row is not the cheapest")
    return f"{note}; {fix}" if fix else note


def emit_json(payload: dict) -> None:
    print(json.dumps(payload, indent=2, ensure_ascii=False, default=str))


# ------------------------------------------------------------------- tables


def _truncate(text: str, width: int) -> str:
    text = text or ""
    return text if len(text) <= width else text[: width - 1] + "…"


def table(rows: Sequence[Sequence[str]], headers: Sequence[str]) -> str:
    """A plain aligned table. No colour, no box drawing — this is read by a
    model as often as by a person, and both do better with plain columns."""
    if not rows:
        return ""
    widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            widths[i] = max(widths[i], len(str(cell)))
    lines = ["  ".join(str(h).ljust(widths[i]) for i, h in enumerate(headers)).rstrip()]
    lines.append("  ".join("-" * widths[i] for i in range(len(headers))))
    for row in rows:
        lines.append("  ".join(str(c).ljust(widths[i]) for i, c in enumerate(row)).rstrip())
    return "\n".join(lines)


def print_offers(offers: Iterable, *, sandbox: bool, show_price: bool,
                 limit: int, total: int | None = None,
                 ranked_by: str = "price") -> None:
    """The human table.

    `show_price` is False in sandbox mode without `--sandbox-ok`: the price
    column is simply absent rather than filled with a caveated number, because
    a number on screen gets read and quoted whatever sits beside it.

    `ranked_by` is printed whenever it is not `price`. Under `--sort distance`
    the rows come back in the API's own order, so the top row is the nearest
    one and not the cheapest; a reader who assumes otherwise gets a wrong
    answer from a table that looks right, which is exactly the failure the
    footer exists to prevent.
    """
    offers = list(offers)[:limit]
    if not offers:
        return

    if sandbox:
        print(SANDBOX_BANNER)
        print()

    headers = ["car", "class", "seats", "bags", "doors", "transmission",
               "agency", "mileage", "cancellation"]
    if show_price:
        headers.insert(6, "price")

    rows = []
    for offer in offers:
        row = [
            _truncate(offer.car.name, 28),
            offer.car.type_name or offer.car.type_code or "?",
            offer.car.passengers if offer.car.passengers is not None else "?",
            offer.car.bags if offer.car.bags is not None else "?",
            offer.car.doors_display or "?",
            offer.car.transmission or "?",
            _truncate(offer.agency_label, 22),
            offer.policy.mileage_display,
            offer.policy.cancel_display,
        ]
        if show_price:
            row.insert(6, (f"{SANDBOX_ROW_PREFIX} " if sandbox else "") + offer.price_label)
        rows.append(row)

    print(table(rows, headers))
    footer = ranking_footer(ranked_by, "re-run with --sort price to rank on price")
    if footer:
        print(f"\n{footer}")
    if total is not None and total > len(offers):
        print(f"\n{len(offers)} of {total} shown — raise --limit for more")


def print_rejections(rejected: dict[str, int], kept: int) -> None:
    """Why an empty (or thin) result is empty.

    The whole point of counting: "0 matched" is a dead end, while naming the
    filter that removed forty-one rows tells the user what to relax.
    """
    if not rejected:
        return
    parts = ", ".join(f"{flag} dropped {count}"
                      for flag, count in sorted(rejected.items(),
                                                key=lambda kv: -kv[1]))
    print(f"\n{kept} matched — {parts}", file=sys.stdout)
